Temporarily comment out dependency to the functional-test plugin as it breaks dependency resolution and compilation - dependency resolution broken, unless I exclude xercesImpl - if I do so, compilation is broken: java.lang.NoClassDefFoundError: Lcom/gargoylesoftware/htmlunit/html/HTMLParser$HtmlUnitDOMBuilder;